name: Build Test & Drop artifacts

on:
  push:
    branches:
      - master
      - main
      - develop

  pull_request:
    branches:
      - master
      - main
      - develop

  workflow_dispatch:

jobs:
  build-test-drop-artifacts:
    name: Build Test & Drop artifacts
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - ubuntu-latest
    
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
      ProjectPath: './WebConfigTransformRunner/WebConfigTransformRunner.csproj'
      Configuration: 'Release'
      Solution: 'WebConfigTransformRunner.sln'
      ArtifactName: 'drop'
      ArtifactPath: 'publish'
    
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Setup .NET 6.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: NuGet Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.csproj') }}

      - name: Nuget Restore
        run: dotnet restore

      - name: Build Solution
        run: |
          dotnet build ${{ env.Solution }} --configuration ${{ env.Configuration }} /p:ContinuousIntegrationBuild=true --no-restore

      - name: Publish Win x64
        shell: pwsh
        run: |
          dotnet publish ${{ env.ProjectPath }} `
               --self-contained `
               --runtime "win-x64" `
               -c ${{ env.Configuration }} `
               -o ./publish.win-x64 `
               -p:PublishTrimmed=true `
               -p:PublishSingleFile=true
          Set-Location ./publish.win-x64
          zip -r ../WebConfigTransformRunner-v${{ env.GITVERSION_SEMVER }}.win-x64.zip *

      - name: Publish Linux x64
        shell: pwsh
        run: |
          dotnet publish ${{ env.ProjectPath }} `
               --self-contained `
               --runtime "linux-x64" `
               -c ${{ env.Configuration }} `
               -o ./publish.linux-x64 `
               -p:PublishTrimmed=true `
               -p:PublishSingleFile=true
          Set-Location ./publish.win-x64
          zip -r ../WebConfigTransformRunner-v${{ env.GITVERSION_SEMVER }}.linux-x64.zip *

      - name: Publish OSX x64
        shell: pwsh
        run: |
          dotnet publish ${{ env.ProjectPath }} `
               --self-contained `
               --runtime "osx-x64" `
               -c ${{ env.Configuration }} `
               -o ./publish.osx-x64 `
               -p:PublishTrimmed=true `
               -p:PublishSingleFile=true
          Set-Location ./publish.osx-x64
          zip -r ../WebConfigTransformRunner-v${{ env.GITVERSION_SEMVER }}.osx-x64.zip *

      - name: Drop Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ArtifactName }}
          path: |
            ./WebConfigTransformRunner-v${{ env.GITVERSION_SEMVER }}.win-x64.zip
            ./WebConfigTransformRunner-v${{ env.GITVERSION_SEMVER }}.linux-x64.zip
            ./WebConfigTransformRunner-v${{ env.GITVERSION_SEMVER }}.osx-x64.zip