trigger: none

pr: none

stages:
  - stage: 'Test_Transform_Win2012'
    jobs:
      - deployment: "Test_Transform_Win2012"
        displayName: 'Test_Transform_Win2012'
        environment:
          name: 'win-server-2012'
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  fetchDepth: 0

                - task: UseDotNet@2
                  displayName: 'Install .NET 6.x SDK'
                  inputs:
                    packageType: sdk
                    version: 6.x

                - powershell: |
                    dotnet tool install --global web.config.transform.tool --version 1.0.5
                  displayName: 'Install web.config.transform.tool'

                - powershell: |
                    cat "Web.config"
                  workingDirectory: '$(Build.SourcesDirectory)/TestData/SetAttributesExample'
                  displayName: 'Print contents of web config'

                - powershell: |
                    dotnet-web-transform "Web.config" "Web.Debug.config" "NewWeb.Debug.config"
                  workingDirectory: '$(Build.SourcesDirectory)/TestData/SetAttributesExample'
                  displayName: 'Transform web.config'

                - powershell: |
                    cat "NewWeb.Debug.config"
                  workingDirectory: '$(Build.SourcesDirectory)/TestData/SetAttributesExample'
                  displayName: 'Print contents of new web config'